services:
  db:
    container_name: postgresPasteBin
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pastebin
    restart: always
    ports:
      - "5433:5432"
    command: -p 5433
    volumes:
      - fastapi_pastebin:/data/postgres
    networks:
      - app-network

  redis:
    container_name: redisPasteBin
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - fastapi_pastebin:/data/redis
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmqPasteBin
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
    - fastapi_pastebin:/data/rabbitmq
    networks:
      - app-network

  app:
    container_name: appPasteBin
    env_file:
      - backend/.env
    build:
      context: .
      dockerfile: ./dockerfile
    depends_on:
      - db
      - redis
      - rabbitmq
    command: ["/app/docker/app.sh"]
    ports:
      - 8001:8000
    networks:
      - app-network

  celery:
    container_name: celeryPasteBin
    env_file:
      - backend/.env
    build:
      context: .
    command: ["/app/docker/celery.sh", "celery"]
    depends_on:
      - redis
    volumes:
      - fastapi_pastebin:/data/celery
    networks:
      - app-network

  flower:
    container_name: flowerPasteBin
    env_file:
      - backend/.env
    build:
      context: .
    command: ["/app/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 5556:5555
    volumes:
      - fastapi_pastebin:/data/flower
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  fastapi_pastebin:
