services:
  db:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge