services:
  db:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pastebin
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - app:/data/postgres

networks:
  app-network:
    driver: bridge

volumes:
  app:
    external: false
